version: '3.8'

services:
  frontend:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    working_dir: /app
    container_name: frontend
    restart: unless-stopped
    environment:
      NODE_ENV: development
    volumes:
      - './:/app'
    command: sh -c "sleep 1; yarn dev"
    deploy:
      resources:
        limits:
          memory: 2048M
        reservations:
          memory: 1048M
    ports:
      - "3000:3000"
    extra_hosts:
      - 'localhost:host-gateway'
