import type { Metadata } from 'next';

import Providers from '@src/infra/providers';

import '@src/ui/styles/globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
  params: { locale },
}: Readonly<{
  children: JSX.Element;
  params: { locale: string };
}>) {
  return (
    <html lang="en">
      <body style={{ margin: 0, padding: 0 }}>
        <Providers locale={locale}>{children}</Providers>
      </body>
    </html>
  );
}
